name:                NeutronScattering
version:             0.1.0.0
github:              "githubuser/NeutronScattering"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/NeutronScattering#readme>

dependencies:
- base >= 4.7 && < 5
- simple-vec3
- mwc-random
- vector # needed?
- STL
- attoparsec
- text
- transformers
- JuicyPixels
- hashtables
- hashable
- tasty
- tasty-hunit
- tasty-quickcheck

library:
  source-dirs: src

executables:
  NeutronScattering-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - NeutronScattering

tests:
  NeutronScattering-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - NeutronScattering
